<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <CentralPackageTransitivePinning>true</CentralPackageTransitivePinning>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.401" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
    <PackageVersion Include="Moq" Version="4.21.0" />
    <PackageVersion Include="TUnit" Version="1.72.10" />
  </ItemGroup>
</Project>